import Head from 'next/head';
import D3Bars from '../components/D3Bars';
import D3BarsMainPage from '../components/D3BarsMainPage'


import styles from '../styles/Home.module.css';


export default function Home() {
  
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Програми та обіцянки політичних партій</title>
          <meta name='description' content='Generated by create next app' />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div>
        
        
        <D3Bars />
        </div>
    
        {/* <ul style={{display: 'flex'}}>
          <li style={ {color: '#009f08'}}>Виконано</li>
          <li style={ {color: '#ff4716', marginLeft: '40px'}}>Не виконано</li>
          <li style={ {color: '#ffd500', marginLeft: '40px'}}>В процесі</li>
          
        </ul> */}
      </div>
    </>
  );
}
